### ISSUE TITLE
go get github.com/BharatKalluri/spotifydl doesn't respond & spotifydl command doesn't work

### ISSUE THREAD

**Issue by Paperbudha** [BharatKalluri/spotifydl#12]
Hi,

I Installed below already in my MAC.

brew install ffmpeg
brew install youtube-dl
brew install gcc
brew install golang

Below is the response when i process below.

ravsharma-mbp:SONGS ravsharma$
ravsharma-mbp:SONGS ravsharma$ spotifydl -h
-bash: spotifydl: command not found
ravsharma-mbp:SONGS ravsharma$ spotifydl -p
-bash: spotifydl: command not found
ravsharma-mbp:SONGS ravsharma$ go get github.com/BharatKalluri/spotifydl
ravsharma-mbp:SONGS ravsharma$ spotifydl
-bash: spotifydl: command not found
ravsharma-mbp:SONGS ravsharma$ spotifydl

what i have missed?

**Comment by BharatKalluri** [comment]
You can use the verbose option to check if the install is progressing or frozen. 

```
go get -u -v github.com/BharatKalluri/spotifydl
```

Also, I've missed the install command in the readme 😅 . After doing `go get` you need to run another command called `go install github.com/BharatKalluri/spotifydl`. This should place the `spotifydl` binary in the $GOPATH/bin.

The long term solution is to use a project like goreleaser to streamline the install process. I am free today to work on this project, I'll probably fix the install process today. Thanks for pointing out this one.
