### ISSUE TITLE
Seems to be downloading same file for different tracks in album

### ISSUE THREAD

**Issue by adamlove86** [BharatKalluri/spotifydl#19]
eg:

```
PS C:\Users\User\Music> spotifydl https://open.spotify.com/album/72qtxILYHUsClxz2jsqb69?si=_8cTBI7tQ4O3TfqNQIdnyQ
Found 3 tracks
Searching and downloading tracks

⇓ Downloading xyz Remix
⇓ Downloading xyz Extended Remix
⇓ Downloading xyz

Download complete!
```
and then

```
PS C:\Users\User\Music> dir


    Directory: C:\Users\User\Music


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        16/03/2021  11:20 AM        5289740 xyz Extended Remix.mp3
-a----        16/03/2021  11:20 AM        5289731 xyz Remix.mp3
-a----        16/03/2021  11:20 AM        5289710 xyz.mp3

```
All tracks are 3:02 long, although slightly different size.

Have tried with individual tracks, as well as without _?si=_ suffix on the link. All files downloaded seem to be the 3:02 version, which is the first track in the album.

**Comment by BharatKalluri** [comment]
Hey @adamlove86 , Thanks for reporting this issue. 
This has been fixed in the [latest release (0.1.1)](https://github.com/BharatKalluri/spotifydl#from-source), installation instructions are in the readme. 

Thanks!
