### ISSUE TITLE
Error while getting repo with golang: cannot use "id,snippet" (type string) as type []string in argument to service.Search.List

### ISSUE THREAD

**Issue by CarpeDN** [BharatKalluri/spotifydl#20]
I get this error when I use the command: go get -u github.com/BharatKalluri/spotifydl

![image](https://user-images.githubusercontent.com/8869338/116294456-ff330000-a765-11eb-83ba-fccb0ebb380e.png)

Please help

**Comment by BharatKalluri** [comment]
Hello @CarpeDN , There was a bug in the 0.1.0 version. This has been fixed in the [latest release (0.1.1)](https://github.com/BharatKalluri/spotifydl#from-source), installation instructions are in the readme. 

Thanks!
